name: CI Build

on:
  pull_request: {}
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
      - run: yarn install
      - name: Cypress - Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: ./cypress.json
          start: yarn start
      - name: Cypress - Firefox
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          config-file: ./cypress.json    
          start: yarn start