name: CI Build

on:
  pull_request: {}
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
      - run: yarn install
      - name: Cypress - Chrome
        run: yarn test:e2e --browser chrome --headless
      - name: Cypress - Firefox  
        run: yarn test:e2e --browser firefox --headless